language: node_js
services:
  - docker
install:
  - echo "ignore npm install"
before_script:
  - docker pull node:12.14-alpine
script: 
  - docker run --rm -w /app -v $(pwd):/app node:12.14-alpine /bin/sh -c "npm i && npm run test"
