language: node_js
services:
  - docker
install:
  - echo "ignore npm install"
before_script:
  - docker pull node:13.14-alpine
  - docker pull node:12.14-alpine
  - docker pull node:11.15-alpine
  - docker pull node:10.22-alpine
script: 
  - docker run --rm -w /app -v $(pwd):/app node:13.14-alpine /bin/sh -c "rm -rf /app/node_modules && npm i && npm run test"
  - docker run --rm -w /app -v $(pwd):/app node:12.14-alpine /bin/sh -c "rm -rf /app/node_modules && npm i && npm run test"
  - docker run --rm -w /app -v $(pwd):/app node:11.15-alpine /bin/sh -c "rm -rf /app/node_modules && npm i && npm run test"
  - docker run --rm -w /app -v $(pwd):/app node:10.22-alpine /bin/sh -c "rm -rf /app/node_modules && npm i && npm run test"
